//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPure.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPure.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields should not be duplicated in the same group.
        /// </summary>
        internal static string API_EXCEPTION_DUPLICATE_FIELD_IN_GROUP {
            get {
                return ResourceManager.GetString("API_EXCEPTION_DUPLICATE_FIELD_IN_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality allowed only in registered version.
        /// </summary>
        internal static string API_EXCEPTION_LICENSE {
            get {
                return ResourceManager.GetString("API_EXCEPTION_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exists in parameters, but there is no such table in the data..
        /// </summary>
        internal static string API_EXCEPTION_NO_TABLE_IN_THE_DATA {
            get {
                return ResourceManager.GetString("API_EXCEPTION_NO_TABLE_IN_THE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters could not be NULL and should contain at least one rule.
        /// </summary>
        internal static string API_EXCEPTION_PARAMETER_NOT_NULL {
            get {
                return ResourceManager.GetString("API_EXCEPTION_PARAMETER_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not contain {1} field.
        /// </summary>
        internal static string API_EXCEPTION_TABLE_NOT_CONTAINS_FIELD {
            get {
                return ResourceManager.GetString("API_EXCEPTION_TABLE_NOT_CONTAINS_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table {0} the field {1} is set to search type {2}, but the field is {3} type. Operation could not be performed..
        /// </summary>
        internal static string API_EXCEPTION_WRONG_FIELD_TYPE {
            get {
                return ResourceManager.GetString("API_EXCEPTION_WRONG_FIELD_TYPE", resourceCulture);
            }
        }
    }
}
