//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPure.Integration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPure.Integration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating statistics.
        /// </summary>
        internal static string CAPTION_CALCULATION_OF_STATISTIC {
            get {
                return ResourceManager.GetString("CAPTION_CALCULATION_OF_STATISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit data....
        /// </summary>
        internal static string CAPTION_IO_COMMIT_DATA {
            get {
                return ResourceManager.GetString("CAPTION_IO_COMMIT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting file to Excel.
        /// </summary>
        internal static string CAPTION_IO_CONVERT_FILE_TO_EXCEL {
            get {
                return ResourceManager.GetString("CAPTION_IO_CONVERT_FILE_TO_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating table structure.
        /// </summary>
        internal static string CAPTION_IO_CREATE_TABLE_STRUCTURE {
            get {
                return ResourceManager.GetString("CAPTION_IO_CREATE_TABLE_STRUCTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data exporting.
        /// </summary>
        internal static string CAPTION_IO_DATA_EXPORTING {
            get {
                return ResourceManager.GetString("CAPTION_IO_DATA_EXPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting complete.
        /// </summary>
        internal static string CAPTION_IO_EXPORT_COMPLETE {
            get {
                return ResourceManager.GetString("CAPTION_IO_EXPORT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing data.
        /// </summary>
        internal static string CAPTION_IO_IMPORTING_DATA {
            get {
                return ResourceManager.GetString("CAPTION_IO_IMPORTING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing display.
        /// </summary>
        internal static string CAPTION_IO_PREPARE_DISPLAYING {
            get {
                return ResourceManager.GetString("CAPTION_IO_PREPARE_DISPLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to import.
        /// </summary>
        internal static string CAPTION_IO_PREPARING_TO_IMPORT {
            get {
                return ResourceManager.GetString("CAPTION_IO_PREPARING_TO_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file.
        /// </summary>
        internal static string CAPTION_IO_READING_FILE {
            get {
                return ResourceManager.GetString("CAPTION_IO_READING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data to local DB.
        /// </summary>
        internal static string CAPTION_IO_SAVING_DATA_TO_LOCAL_DB {
            get {
                return ResourceManager.GetString("CAPTION_IO_SAVING_DATA_TO_LOCAL_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing for display.
        /// </summary>
        internal static string CAPTION_PREPARING_FOR_DISPLAY {
            get {
                return ResourceManager.GetString("CAPTION_PREPARING_FOR_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but you do not have the correct ACE.OLEDB driver installed.
        /// </summary>
        internal static string EXCEPTION_ACEOLEDB_NOTREGISTERED {
            get {
                return ResourceManager.GetString("EXCEPTION_ACEOLEDB_NOTREGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create table in local DB.
        /// </summary>
        internal static string EXCEPTION_COULD_NOT_CREATE_TABLE {
            get {
                return ResourceManager.GetString("EXCEPTION_COULD_NOT_CREATE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t open a file.
        /// </summary>
        internal static string EXCEPTION_IO_CANNOT_CONNECT_TO_FILE {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_CANNOT_CONNECT_TO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to server.
        /// </summary>
        internal static string EXCEPTION_IO_CANNOT_CONNECT_TO_SERVER {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_CANNOT_CONNECT_TO_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve data from the DataBase..
        /// </summary>
        internal static string EXCEPTION_IO_CANNOT_GET_DATA_FROM_DB {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_CANNOT_GET_DATA_FROM_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t extract database names.
        /// </summary>
        internal static string EXCEPTION_IO_CANNOT_GET_DATABASE_LIST {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_CANNOT_GET_DATABASE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Failed to retrieve preview data from the Database..
        /// </summary>
        internal static string EXCEPTION_IO_CANNOT_GET_PREVIEW {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_CANNOT_GET_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t extract table names.
        /// </summary>
        internal static string EXCEPTION_IO_CANNOT_GET_TABLES_LIST {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_CANNOT_GET_TABLES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t open sheet.
        /// </summary>
        internal static string EXCEPTION_IO_CANNOT_OPEN_EXCEL_SHEET {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_CANNOT_OPEN_EXCEL_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data could not be exported to {0}.
        /// </summary>
        internal static string EXCEPTION_IO_DATA_COULD_NOT_BE_EXPORTED_TO {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_DATA_COULD_NOT_BE_EXPORTED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable should not be null.
        /// </summary>
        internal static string EXCEPTION_IO_DATATABLE_SHOULD_NOT_BE_NULL {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_DATATABLE_SHOULD_NOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for export is empty.
        /// </summary>
        internal static string EXCEPTION_IO_EMPTY_EXPORT_DATA {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_EMPTY_EXPORT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error happens during the import.
        /// </summary>
        internal static string EXCEPTION_IO_ERROR_ON_IMPORT {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_ERROR_ON_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid database name.
        /// </summary>
        internal static string EXCEPTION_IO_INVALID_DB_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_INVALID_DB_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name should not be empty.
        /// </summary>
        internal static string EXCEPTION_IO_INVALID_EXPORT_FILE_NAME {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_INVALID_EXPORT_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is in wrong format.
        /// </summary>
        internal static string EXCEPTION_IO_PARAMETERS_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_PARAMETERS_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table exists in database. Export could not be completed.
        /// </summary>
        internal static string EXCEPTION_IO_TABLE_EXISTS_EXPORT_FAIL {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_TABLE_EXISTS_EXPORT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name should be filled.
        /// </summary>
        internal static string EXCEPTION_IO_TABLE_NAME_SHOULD_BE {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_TABLE_NAME_SHOULD_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportToExcel: This excel file type does not support more than 65536 records. Please select another format.
        /// </summary>
        internal static string EXCEPTION_IO_TOO_MUCH_DATA_FOR_OLD_EXCEL {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_TOO_MUCH_DATA_FOR_OLD_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date delimiter could not be equal to text qualifier.
        /// </summary>
        internal static string EXCEPTION_IOTXT_DATE_TEXT_QUALIFIER {
            get {
                return ResourceManager.GetString("EXCEPTION_IOTXT_DATE_TEXT_QUALIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal delimiter could not be equal to date delimiter.
        /// </summary>
        internal static string EXCEPTION_IOTXT_DECIMAL_DATE_DELIMETER {
            get {
                return ResourceManager.GetString("EXCEPTION_IOTXT_DECIMAL_DATE_DELIMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal delimiter could not be equal to text qualifier.
        /// </summary>
        internal static string EXCEPTION_IOTXT_DECIMAL_TEXT_QUALIFIER {
            get {
                return ResourceManager.GetString("EXCEPTION_IOTXT_DECIMAL_TEXT_QUALIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal delimiter could not be equal to time delimiter.
        /// </summary>
        internal static string EXCEPTION_IOTXT_DECIMAL_TIME_DELIMETER {
            get {
                return ResourceManager.GetString("EXCEPTION_IOTXT_DECIMAL_TIME_DELIMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field delimiter could not be equal to date delimiter.
        /// </summary>
        internal static string EXCEPTION_IOTXT_FIELD_DATE_DELIMETER {
            get {
                return ResourceManager.GetString("EXCEPTION_IOTXT_FIELD_DATE_DELIMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field delimiter could not be equal to decimal delimiter.
        /// </summary>
        internal static string EXCEPTION_IOTXT_FIELD_DECIMAL_DELIMETERS {
            get {
                return ResourceManager.GetString("EXCEPTION_IOTXT_FIELD_DECIMAL_DELIMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field delimiter could not be equal to text qualifier.
        /// </summary>
        internal static string EXCEPTION_IOTXT_FIELD_TEXT_QUALIFIER {
            get {
                return ResourceManager.GetString("EXCEPTION_IOTXT_FIELD_TEXT_QUALIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field delimiter could not be equal to time delimiter.
        /// </summary>
        internal static string EXCEPTION_IOTXT_FIELD_TIME_DELIMETER {
            get {
                return ResourceManager.GetString("EXCEPTION_IOTXT_FIELD_TIME_DELIMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import options are not set.
        /// </summary>
        internal static string EXCEPTION_IOTXT_OPTIONS_NOT_SET {
            get {
                return ResourceManager.GetString("EXCEPTION_IOTXT_OPTIONS_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time delimiter could not be equal to date delimiter.
        /// </summary>
        internal static string EXCEPTION_IOTXT_TIME_DATE_DELIMETER {
            get {
                return ResourceManager.GetString("EXCEPTION_IOTXT_TIME_DATE_DELIMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time delimiter could not be equal to text qualifier.
        /// </summary>
        internal static string EXCEPTION_IOTXT_TIME_TEXT_QUALIFIER {
            get {
                return ResourceManager.GetString("EXCEPTION_IOTXT_TIME_TEXT_QUALIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data size is too big, Please use 64bit version to process that data.
        /// </summary>
        internal static string EXCEPTION_OUTOFMEMORY {
            get {
                return ResourceManager.GetString("EXCEPTION_OUTOFMEMORY", resourceCulture);
            }
        }
    }
}
