//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPure.AddressVerification.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPure.AddressVerification.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASS is only available for USA.
        /// </summary>
        internal static string API_EXCEPTION_CASSONLYWITHUSA {
            get {
                return ResourceManager.GetString("API_EXCEPTION_CASSONLYWITHUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure the Locality is selected.
        /// </summary>
        internal static string API_EXCEPTION_LOCALITYFORCASS {
            get {
                return ResourceManager.GetString("API_EXCEPTION_LOCALITYFORCASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough credits available to process {0} records.
        /// </summary>
        internal static string API_EXCEPTION_NOTENOUGHCREDITS {
            get {
                return ResourceManager.GetString("API_EXCEPTION_NOTENOUGHCREDITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address verification in progress.
        /// </summary>
        internal static string CAPTION_ADDRVERIFY_PROGRESS {
            get {
                return ResourceManager.GetString("CAPTION_ADDRVERIFY_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should set Longitude and Latitude columns!.
        /// </summary>
        internal static string EXCEPTION_ADDREVERSEGEOCODE_COLUMNS {
            get {
                return ResourceManager.GetString("EXCEPTION_ADDREVERSEGEOCODE_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should set address and zip column or address and city and state column!.
        /// </summary>
        internal static string EXCEPTION_ADDRVERIFY_COLUMNS {
            get {
                return ResourceManager.GetString("EXCEPTION_ADDRVERIFY_COLUMNS", resourceCulture);
            }
        }
    }
}
