//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPure.Cleansing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPure.Cleansing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleansing result can not be processed.
        /// </summary>
        internal static string EXCEPTION_CLEAN_RESULT_NOT_PROCESSED {
            get {
                return ResourceManager.GetString("EXCEPTION_CLEAN_RESULT_NOT_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleansing exeption(s): {0}.
        /// </summary>
        internal static string EXCEPTION_CLEANSINGCUMMULATIVEERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_CLEANSINGCUMMULATIVEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean table error..
        /// </summary>
        internal static string EXCEPTION_CLEANTABLEERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_CLEANTABLEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings file error..
        /// </summary>
        internal static string EXCEPTION_EXPORT_SETTING_ERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_EXPORT_SETTING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings file error..
        /// </summary>
        internal static string EXCEPTION_IMPORT_SETTING_ERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_IMPORT_SETTING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination path and file name cannot be null or empty.
        /// </summary>
        internal static string EXCEPTION_PATHANDFILE {
            get {
                return ResourceManager.GetString("EXCEPTION_PATHANDFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings cannot be null.
        /// </summary>
        internal static string EXCEPTION_SETTINGSNOTNULL {
            get {
                return ResourceManager.GetString("EXCEPTION_SETTINGSNOTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source data table cannot be null.
        /// </summary>
        internal static string EXCEPTION_SOURCEDTNOTNULL {
            get {
                return ResourceManager.GetString("EXCEPTION_SOURCEDTNOTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic calculation error..
        /// </summary>
        internal static string EXCEPTION_STATISTICERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_STATISTICERROR", resourceCulture);
            }
        }
    }
}
