//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPure.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPure.Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Required.
        /// </summary>
        internal static string COMMON_DICTIONARY_NOT_REQUIRED {
            get {
                return ResourceManager.GetString("COMMON_DICTIONARY_NOT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit name of system library..
        /// </summary>
        internal static string DICTIONARY_EXCEPTION_CANNOT_EDIT_SYSTEM_DICTIONARY {
            get {
                return ResourceManager.GetString("DICTIONARY_EXCEPTION_CANNOT_EDIT_SYSTEM_DICTIONARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search value cannot be empty. Please fill the search value.
        /// </summary>
        internal static string DICTIONARY_EXCEPTION_FILL_SEARCH_VALUE {
            get {
                return ResourceManager.GetString("DICTIONARY_EXCEPTION_FILL_SEARCH_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This search value exists in the dictionary. Please set another search value.
        /// </summary>
        internal static string DICTIONARY_EXCEPTION_SEARCH_VALUE_EXISTS {
            get {
                return ResourceManager.GetString("DICTIONARY_EXCEPTION_SEARCH_VALUE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library with the same name already exists. Please enter another name.
        /// </summary>
        internal static string DICTIONARY_EXCEPTION_SELECT_ANOTHER_LIBRARY_NAME {
            get {
                return ResourceManager.GetString("DICTIONARY_EXCEPTION_SELECT_ANOTHER_LIBRARY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This search value exists in the library. Please set another search value.
        /// </summary>
        internal static string DICTIONARY_EXCEPTION_SELECT_ANOTHER_SEARCH_VALUE {
            get {
                return ResourceManager.GetString("DICTIONARY_EXCEPTION_SELECT_ANOTHER_SEARCH_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary not defined. Please select the dictionary.
        /// </summary>
        internal static string DICTIONARY_EXCEPTION_SELECT_DICTIONARY {
            get {
                return ResourceManager.GetString("DICTIONARY_EXCEPTION_SELECT_DICTIONARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create table in local DB.
        /// </summary>
        internal static string EXCEPTION_COULD_NOT_CREATE_TABLE {
            get {
                return ResourceManager.GetString("EXCEPTION_COULD_NOT_CREATE_TABLE", resourceCulture);
            }
        }
    }
}
