// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinPure.Configuration.Infrastructure;

namespace WinPure.Configuration.Migrations
{
    [DbContext(typeof(WinPureConfigurationContext))]
    [Migration("20240102221651_AddEntityResolutionMappingSettings")]
    partial class AddEntityResolutionMappingSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("WinPure.Configuration.Models.Database.AutomationConfigurationStepEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parameter1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameter2")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("StepId");

                    b.ToTable("AutomationConfigurationSteps");
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.AutomationHeaderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AutomationHeaders");
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.AutomationLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfRun")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ExecutionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Successful")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("AutomationLogs");
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.AutomationScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("DayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeeklyTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("AutomationSchedules");
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.AutomationStepDictionaryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AutomationStepsDictionary");
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.ConnectionSettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Settings")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConnectionSettings");
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.DictionaryDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DictionaryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplaceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId");

                    b.ToTable("DictionaryData");
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.DictionaryNameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DictionaryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DictionaryName");
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.EntityResolutionMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConflictEntityTypes")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExactMatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrerequisiteEntityTypes")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageGroup")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EntityResolutionMapping");
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.ProperCaseSettingEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ProperCaseSettings");
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.RecentProjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'localtime')");

                    b.Property<DateTime>("LastUpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'localtime')");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecentProjects");
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.AutomationConfigurationStepEntity", b =>
                {
                    b.HasOne("WinPure.Configuration.Models.Database.AutomationHeaderEntity", "Configuration")
                        .WithMany("ConfigurationSteps")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinPure.Configuration.Models.Database.AutomationStepDictionaryEntity", "Step")
                        .WithMany("ConfigurationSteps")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.AutomationLogEntity", b =>
                {
                    b.HasOne("WinPure.Configuration.Models.Database.AutomationScheduleEntity", "Schedule")
                        .WithMany("Logs")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.AutomationScheduleEntity", b =>
                {
                    b.HasOne("WinPure.Configuration.Models.Database.AutomationHeaderEntity", "Configuration")
                        .WithMany("Schedules")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WinPure.Configuration.Models.Database.DictionaryDataEntity", b =>
                {
                    b.HasOne("WinPure.Configuration.Models.Database.DictionaryNameEntity", "Dictionary")
                        .WithMany("DictionaryData")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
