//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPure.Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPure.Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Project....
        /// </summary>
        internal static string CAPTION_OPEN_PROJECT {
            get {
                return ResourceManager.GetString("CAPTION_OPEN_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Project....
        /// </summary>
        internal static string CAPTION_SAVE_PROJECT {
            get {
                return ResourceManager.GetString("CAPTION_SAVE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project cannot be created.
        /// </summary>
        internal static string EXCEPTION_NEW_PROJECT_CANNOT_CREATE {
            get {
                return ResourceManager.GetString("EXCEPTION_NEW_PROJECT_CANNOT_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project cannot be loaded. Project maybe corrupt or in wrong format..
        /// </summary>
        internal static string EXCEPTION_PROJECT_FILE_CORRUPTED {
            get {
                return ResourceManager.GetString("EXCEPTION_PROJECT_FILE_CORRUPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project Error.
        /// </summary>
        internal static string EXCEPTION_PROJECT_OPEN_CAPTION {
            get {
                return ResourceManager.GetString("EXCEPTION_PROJECT_OPEN_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project cannot be saved.
        /// </summary>
        internal static string EXCEPTION_PROJECT_SAVE_ERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_PROJECT_SAVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project cannot be loaded. Wrong project file format..
        /// </summary>
        internal static string EXCEPTION_PROJECT_WRONG_FILE_FORMAT {
            get {
                return ResourceManager.GetString("EXCEPTION_PROJECT_WRONG_FILE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should set project name before save.
        /// </summary>
        internal static string EXCEPTION_SET_PROJECT_NAME_BEFORE_SAVING_PROJECT {
            get {
                return ResourceManager.GetString("EXCEPTION_SET_PROJECT_NAME_BEFORE_SAVING_PROJECT", resourceCulture);
            }
        }
    }
}
