namespace WinPure.Configuration.Helper;

internal static partial class DatabaseInitiator
{
    static List<StatisticPatternEntity> GetStatisticPatterns =>
    [
        new StatisticPatternEntity { Name = "Canada Postal Code", FieldType = "Zip", Pattern = @"^(([A-Za-z]\d[A-Za-z][\s\.\-]?(|-)?\d[A-Za-z]\d)|[A-Za-z]{1,2}\d{1,2}[A-Za-z]? \d[A-Za-z]{2})$", Description = "Validates Canadian postal codes" },
        new StatisticPatternEntity { Name = "Credit Card", FieldType = "Misc", Pattern = @"^(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})$", Description = "Validates credit card numbers" },
        new StatisticPatternEntity { Name = "Date\\Time", FieldType = "DateTime", Pattern = @"^(?=\d)(?:(?!(?:(?:0?[5-9]|1[0-4])(?:\.|-|\/)10(?:\.|-|\/)(?:1582))|(?:(?:0?[3-9]|1[0-3])(?:\.|-|\/)0?9(?:\.|-|\/)(?:1752)))(31(?!(?:\.|-|\/)(?:0?[2469]|11))|30(?!(?:\.|-|\/)0?2)|(?:29(?:(?!(?:\.|-|\/)0?2(?:\.|-|\/))|(?=\D0?2\D(?:(?!000[04]|(?:(?:1[^0-6]|[2468][^048]|[3579][^26])00))(?:(?:(?:\d\d)(?:[02468][048]|[13579][26])(?!\x20BC))|(?:00(?:42|3[0369]|2[147]|1[258]|09)\x20BC))))))|2[0-8]|1\d|0?[1-9])([-.\/])(1[012]|(?:0?[1-9]))\2((?=(?:00(?:4[0-5]|[0-3]?\d)\x20BC)|(?:\d{4}(?:$|(?=\x20\d)\x20)))\d{4}(?:\x20BC)?)(?:$|(?=\x20\d)\x20))?((?:(?:0?[1-9]|1[012])(?::[0-5]\d){0,2}(?:\x20[aApP][mM]))|(?:[01]\d|2[0-3])(?::[0-5]\d){1,2})?$", Description = "Validates various types of Dates and time formats" },
        new StatisticPatternEntity { Name = "Email", FieldType = "Email", Pattern = @"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", Description = "Validates email addresses" },
        new StatisticPatternEntity { Name = "Gender", FieldType = "Misc", Pattern = @"^male$|^female$", Description = "Matching the exact words \"male\" or \"female\"" },
        new StatisticPatternEntity { Name = "GUID", FieldType = "Misc", Pattern = @"^[{|\(]?[0-9a-fA-F]{8}[-]?([0-9a-fA-F]{4}[-]?){3}[0-9a-fA-F]{12}[\)|}]?$", Description = "Validates GUID (Globally Unique Identifier) or UUID (Universally Unique Identifiers" },
        new StatisticPatternEntity { Name = "HEX Number", FieldType = "Number", Pattern = @"^([0-9a-fA-F]){8}$", Description = "Matching exactly 8 hexadecimal characters" },
        new StatisticPatternEntity { Name = "Http", FieldType = "Misc;Url", Pattern = @"^(http|https)://", Description = "Validating the beginning of a URL that starts with either http:// or https://" },
        new StatisticPatternEntity { Name = "IBAN", FieldType = "IBAN;BankAccount;Account", Pattern = @"[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{4}[0-9]{7}([a-zA-Z0-9]?){0,16}", Description = "Validates International Bank Account Numbers (IBAN)" },
        new StatisticPatternEntity { Name = "International Phone Number", FieldType = "Phone", Pattern = @"^\+((?:9[679]|8[035789]|6[789]|5[90]|42|3[578]|2[1-689])|9[0-58]|8[1246]|6[0-6]|5[1-8]|4[013-9]|3[0-469]|2[70]|7|1)(?:\W*\d){0,13}\d$", Description = "Validates phone numbers with an international dialing code" },
        new StatisticPatternEntity { Name = "IP address", FieldType = "Misc", Pattern = @"([0-9]{1,3}\.?){4}", Description = "Matching IP addresses-like patterns" },
        new StatisticPatternEntity { Name = "Registro Federal de Contribuyentes (RFC)", FieldType = "Misc", Pattern = @"^([A-Z|a-z|&amp;]{3}\d{2}((0[1-9]|1[012])(0[1-9]|1\d|2[0-8])|(0[13456789]|1[012])(29|30)|(0[13578]|1[02])31)|([02468][048]|[13579][26])0229)(\w{2})([A|a|0-9]{1})$|^([A-Z|a-z]{4}\d{2}((0[1-9]|1[012])(0[1-9]|1\d|2[0-8])|(0[13456789]|1[012])(29|30)|(0[13578]|1[02])31)|([02468][048]|[13579][26])0229)((\w{2})([A|a|0-9]{1})){0,3}$", Description = "Validates tax identification number in Mexico" },
        new StatisticPatternEntity { Name = "UK National Insurance Number (NINo)", FieldType = "SocialSecurity", Pattern = @"^[A-CEGHJ-PR-TW-Z]{1}[A-CEGHJ-NPR-TW-Z]{1}[0-9]{6}[A-DFM]{0,1}$", Description = "Validates UK National Insurance numbers (NINo)" },
        new StatisticPatternEntity { Name = "UK Phone Number", FieldType = "Phone", Pattern = @"^(\+44\s?7\d{3}|\(?0\d{2,4}\)?)\s?\d{3,4}\s?\d{3,4}(\s?(x|ext\.?)\s?\d+)?$", Description = "Validates UK phone numbers" },
        new StatisticPatternEntity { Name = "UK Postcode", FieldType = "Zip", Pattern = @"(((^[BEGLMNS][1-9]\d?)|(^W[2-9])|(^(A[BL]|B[ABDHLNRST]|C[ABFHMORTVW]|D[ADEGHLNTY]|E[HNX]|F[KY]|G[LUY]|H[ADGPRSUX]|I[GMPV]|JE|K[ATWY]|L[ADELNSU]|M[EKL]|N[EGNPRW]|O[LX]|P[AEHLOR]|R[GHM]|S[AEGKL-PRSTWY]|T[ADFNQRSW]|UB|W[ADFNRSV]|YO|ZE)\d\d?)|(^W1[A-HJKSTUW0-9])|(((^WC[1-2])|(^EC[1-4])|(^SW1))[ABEHMNPRVWXY]))(\s*)?([0-9][ABD-HJLNP-UW-Z]{2}))|(^GIR\s?0AA)$", Description = "Validates UK postcodes" },
        new StatisticPatternEntity { Name = "URL", FieldType = "Url", Pattern = @"(((file|gopher|news|nntp|telnet|http|ftp|https|ftps|sftp)://)|(www\.))+(([a-zA-Z0-9\._-]+\.[a-zA-Z]{2,6})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(/[a-zA-Z0-9\&amp;%_\./-~-]*)?", Description = "Validates all URL types" },
        new StatisticPatternEntity { Name = "US 5 or 9 Digit Zip Code", FieldType = "Address", Pattern = @"^\d{5}(?:-\d{4})?$", Description = "Address (Global)" },
        new StatisticPatternEntity { Name = "US & CA Zip Code", FieldType = "Zip", Pattern = @"^((\d{5}((|-)-\d{4})?)|([A-Za-z]\d[A-Za-z][\s\.\-]?(|-)?\d[A-Za-z]\d)|[A-Za-z]{1,2}\d{1,2}[A-Za-z]? \d[A-Za-z]{2})$", Description = "Validates Canadian & US Zip Codes" },
        new StatisticPatternEntity { Name = "US Full Address", FieldType = "Address", Pattern = @"^(\d+\s+[a-zA-Z\s#.\d-]+)\s+([a-zA-Z\s]+)\s+([A-Z]{2,}\s+\d{5}(?:-\d{4})?)?$", Description = "For standard US-style address format consisting of a street address, city, state, and postal code" },
        new StatisticPatternEntity { Name = "US Phone Number", FieldType = "Phone", Pattern = @"^((\(\d{3}\) ?)|(\d{3}[- \.]))?\d{3}[- \.]\d{4}(\s(x\d+)?){0,1}$", Description = "Validates US phone numbers" },
        new StatisticPatternEntity { Name = "US Social Security Number (SSN)", FieldType = "SocialSecurity", Pattern = @"^(?!000)([0-6]\d{2}|7([0-6]\d|7[012]))([ -]?)(?!00)\d\d\3(?!0000)\d{4}$", Description = "Validates US Social Security Numbers" },
        new StatisticPatternEntity { Name = "US States - Codes", FieldType = "State", Pattern = @"^(?:AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY)$", Description = "Validates US State Codes" },
        new StatisticPatternEntity { Name = "US States - Names", FieldType = "State", Pattern = @"^(?:Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Mississippi|Missouri|Montana|Nebraska|Nevada|New\\sHampshire|New\\sJersey|New\\sMexico|New\\sYork|North\\sCarolina|North\\sDakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode\\sIsland|South\\sCarolina|South\\sDakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West\\sVirginia|Wisconsin|Wyoming)$", Description = "Validates US State Names" },
        new StatisticPatternEntity { Name = "US Zip Code", FieldType = "Zip", Pattern = @"(^\d{5}$)|(^\d{5}-\d{4}$)", Description = "Validates US Zip Codes" },
    ];
}