//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPure.Matching.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPure.Matching.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding duplicates into result..
        /// </summary>
        internal static string API_CAPTION_ADD_DUPLICATES_TO_RESULT {
            get {
                return ResourceManager.GetString("API_CAPTION_ADD_DUPLICATES_TO_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating characters map.
        /// </summary>
        internal static string API_CAPTION_CALCULATE_CHARACTESS_MAP {
            get {
                return ResourceManager.GetString("API_CAPTION_CALCULATE_CHARACTESS_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking input parameters.
        /// </summary>
        internal static string API_CAPTION_CHECK_INPUT_PARAMETERS {
            get {
                return ResourceManager.GetString("API_CAPTION_CHECK_INPUT_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clusters formation ({0} Items left). Group {1}/{2} processing..
        /// </summary>
        internal static string API_CAPTION_CLUSTER_FORMATION {
            get {
                return ResourceManager.GetString("API_CAPTION_CLUSTER_FORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine possible groups ({0} broken links) Group {1}/{2}.
        /// </summary>
        internal static string API_CAPTION_COMBINE_GROUPS {
            get {
                return ResourceManager.GetString("API_CAPTION_COMBINE_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating items to matching.
        /// </summary>
        internal static string API_CAPTION_CREATING_ITEMS_FOR_MATCHING {
            get {
                return ResourceManager.GetString("API_CAPTION_CREATING_ITEMS_FOR_MATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling result table.
        /// </summary>
        internal static string API_CAPTION_FILLING_RESULT_TABLE {
            get {
                return ResourceManager.GetString("API_CAPTION_FILLING_RESULT_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding duplicates of Rule {0}.
        /// </summary>
        internal static string API_CAPTION_FINDING_DUPLICATES {
            get {
                return ResourceManager.GetString("API_CAPTION_FINDING_DUPLICATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding duplicates.
        /// </summary>
        internal static string API_CAPTION_FINDING_DUPLICATES_MIX {
            get {
                return ResourceManager.GetString("API_CAPTION_FINDING_DUPLICATES_MIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating items.
        /// </summary>
        internal static string API_CAPTION_INITIATE_ITEMS {
            get {
                return ResourceManager.GetString("API_CAPTION_INITIATE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items in {1} clusters processing. Group {2}/{3} processing.
        /// </summary>
        internal static string API_CAPTION_ITEMS_IN_CLUSTERS {
            get {
                return ResourceManager.GetString("API_CAPTION_ITEMS_IN_CLUSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching data for Rule {0}.
        /// </summary>
        internal static string API_CAPTION_MATCHING_DATA {
            get {
                return ResourceManager.GetString("API_CAPTION_MATCHING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching data. Group {0}/{1} processing.
        /// </summary>
        internal static string API_CAPTION_MATCHING_DATA_CROUP_OF {
            get {
                return ResourceManager.GetString("API_CAPTION_MATCHING_DATA_CROUP_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was successfully cancelled.
        /// </summary>
        internal static string API_CAPTION_OPERATION_CANCELLED {
            get {
                return ResourceManager.GetString("API_CAPTION_OPERATION_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing result table.
        /// </summary>
        internal static string API_CAPTION_PREPARE_RESULT_TABLE {
            get {
                return ResourceManager.GetString("API_CAPTION_PREPARE_RESULT_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the result.
        /// </summary>
        internal static string API_CAPTION_RETURN_RESULT_TABLE {
            get {
                return ResourceManager.GetString("API_CAPTION_RETURN_RESULT_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching broken links ({0} items). Group {1}/{2} processed.
        /// </summary>
        internal static string API_CAPTION_SEARCHING_BROKEN_LINKS {
            get {
                return ResourceManager.GetString("API_CAPTION_SEARCHING_BROKEN_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinct records count.
        /// </summary>
        internal static string API_REPORT_DISTINCT_RECORD {
            get {
                return ResourceManager.GetString("API_REPORT_DISTINCT_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched records count.
        /// </summary>
        internal static string API_REPORT_MATCHED_RECORDS {
            get {
                return ResourceManager.GetString("API_REPORT_MATCHED_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare data....
        /// </summary>
        internal static string CAPTION_DATA_PREPARING {
            get {
                return ResourceManager.GetString("CAPTION_DATA_PREPARING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updating... Please Wait.
        /// </summary>
        internal static string CAPTION_DATA_UPDATING_WAIT {
            get {
                return ResourceManager.GetString("CAPTION_DATA_UPDATING_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add matching column(s) here.
        /// </summary>
        internal static string CAPTION_DUMMYCONDITION {
            get {
                return ResourceManager.GetString("CAPTION_DUMMYCONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing for display.
        /// </summary>
        internal static string CAPTION_PREPARING_FOR_DISPLAY {
            get {
                return ResourceManager.GetString("CAPTION_PREPARING_FOR_DISPLAY", resourceCulture);
            }
        }
    }
}
