//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPure.DataService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPure.DataService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address verification in progress.
        /// </summary>
        internal static string CAPTION_ADDRVERIFY_PROGRESS {
            get {
                return ResourceManager.GetString("CAPTION_ADDRVERIFY_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating statistics.
        /// </summary>
        internal static string CAPTION_CALCULATION_OF_STATISTIC {
            get {
                return ResourceManager.GetString("CAPTION_CALCULATION_OF_STATISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column(s) copying....
        /// </summary>
        internal static string CAPTION_COLUMNS_COPYING {
            get {
                return ResourceManager.GetString("CAPTION_COLUMNS_COPYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns are renamed.
        /// </summary>
        internal static string CAPTION_COLUMNS_RENAMING {
            get {
                return ResourceManager.GetString("CAPTION_COLUMNS_RENAMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string CAPTION_COMPLETE {
            get {
                return ResourceManager.GetString("CAPTION_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Cleaning - Please Wait.
        /// </summary>
        internal static string CAPTION_DATA_CLEANING {
            get {
                return ResourceManager.GetString("CAPTION_DATA_CLEANING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data exporting....
        /// </summary>
        internal static string CAPTION_DATA_EXPORTING {
            get {
                return ResourceManager.GetString("CAPTION_DATA_EXPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processing...Please Wait.
        /// </summary>
        internal static string CAPTION_DATA_PROCESSING_WAIT {
            get {
                return ResourceManager.GetString("CAPTION_DATA_PROCESSING_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updating... Please Wait.
        /// </summary>
        internal static string CAPTION_DATA_UPDATING_WAIT {
            get {
                return ResourceManager.GetString("CAPTION_DATA_UPDATING_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data importing....
        /// </summary>
        internal static string CAPTION_DATAIMPORTING {
            get {
                return ResourceManager.GetString("CAPTION_DATAIMPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically assigning the master records...Please Wait.
        /// </summary>
        internal static string CAPTION_DEFINING_MASTER_RECORD_WAIT {
            get {
                return ResourceManager.GetString("CAPTION_DEFINING_MASTER_RECORD_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export complete.
        /// </summary>
        internal static string CAPTION_EXPORT_COMPLETE {
            get {
                return ResourceManager.GetString("CAPTION_EXPORT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export error.
        /// </summary>
        internal static string CAPTION_EXPORT_ERROR {
            get {
                return ResourceManager.GetString("CAPTION_EXPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching data....
        /// </summary>
        internal static string CAPTION_MATCHING_DATA {
            get {
                return ResourceManager.GetString("CAPTION_MATCHING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1 of 10 - Extracting Data.
        /// </summary>
        internal static string CAPTION_MATCHING_STEP1OF10 {
            get {
                return ResourceManager.GetString("CAPTION_MATCHING_STEP1OF10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was successfully cancelled.
        /// </summary>
        internal static string CAPTION_OPERATION_CANCELLED {
            get {
                return ResourceManager.GetString("CAPTION_OPERATION_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare parameters.
        /// </summary>
        internal static string CAPTION_PARAMETERS_PREPARING {
            get {
                return ResourceManager.GetString("CAPTION_PARAMETERS_PREPARING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing data for export.
        /// </summary>
        internal static string CAPTION_PREPARE_DATA_FOR_EXPORT {
            get {
                return ResourceManager.GetString("CAPTION_PREPARE_DATA_FOR_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing for display.
        /// </summary>
        internal static string CAPTION_PREPARING_FOR_DISPLAY {
            get {
                return ResourceManager.GetString("CAPTION_PREPARING_FOR_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing audit log….
        /// </summary>
        internal static string CAPTION_PREPARINGAUDITLOGS {
            get {
                return ResourceManager.GetString("CAPTION_PREPARINGAUDITLOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing report.
        /// </summary>
        internal static string CAPTION_REPORT_PREPARING {
            get {
                return ResourceManager.GetString("CAPTION_REPORT_PREPARING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing result.
        /// </summary>
        internal static string CAPTION_RESULT_PREPARING {
            get {
                return ResourceManager.GetString("CAPTION_RESULT_PREPARING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes….
        /// </summary>
        internal static string CAPTION_SAVINGCHANGES {
            get {
                return ResourceManager.GetString("CAPTION_SAVINGCHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating statistics...
        /// </summary>
        internal static string CAPTION_STATISTIC_PROCESSING {
            get {
                return ResourceManager.GetString("CAPTION_STATISTIC_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column unique values could not be calculated.
        /// </summary>
        internal static string EXCEPTION_CANNOT_CALCULATE_UNIQUE_VALUES {
            get {
                return ResourceManager.GetString("EXCEPTION_CANNOT_CALCULATE_UNIQUE_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get data from table.
        /// </summary>
        internal static string EXCEPTION_CANNOT_GET_DATA_FROM_TABLE {
            get {
                return ResourceManager.GetString("EXCEPTION_CANNOT_GET_DATA_FROM_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get Word Manager parameters..
        /// </summary>
        internal static string EXCEPTION_CANNOT_GET_WORDMANAGER_PARAMETERS {
            get {
                return ResourceManager.GetString("EXCEPTION_CANNOT_GET_WORDMANAGER_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save Clean settings..
        /// </summary>
        internal static string EXCEPTION_CANNOT_SAVE_CLEAN_SETTINGS {
            get {
                return ResourceManager.GetString("EXCEPTION_CANNOT_SAVE_CLEAN_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save Word manager parameters.
        /// </summary>
        internal static string EXCEPTION_CANNOT_SAVE_WORDMANAGER_PARAMETERS {
            get {
                return ResourceManager.GetString("EXCEPTION_CANNOT_SAVE_WORDMANAGER_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean operation failed..
        /// </summary>
        internal static string EXCEPTION_CLEAN_FAILED {
            get {
                return ResourceManager.GetString("EXCEPTION_CLEAN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean matrix cannot be saved..
        /// </summary>
        internal static string EXCEPTION_CLEAN_MATRIX_NOT_SAVED {
            get {
                return ResourceManager.GetString("EXCEPTION_CLEAN_MATRIX_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column could not be added.
        /// </summary>
        internal static string EXCEPTION_COLUMN_ADD_ERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_COLUMN_ADD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on copy column(s).
        /// </summary>
        internal static string EXCEPTION_COLUMN_COPY_ERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_COLUMN_COPY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column with the same name exists in the table.
        /// </summary>
        internal static string EXCEPTION_COLUMN_EXISTS_IN_TABLE {
            get {
                return ResourceManager.GetString("EXCEPTION_COLUMN_EXISTS_IN_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column could not be removed.
        /// </summary>
        internal static string EXCEPTION_COLUMN_REMOVE_ERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_COLUMN_REMOVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column could not be renamed.
        /// </summary>
        internal static string EXCEPTION_COLUMN_RENAME_ERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_COLUMN_RENAME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not prepare parameters for matching.
        /// </summary>
        internal static string EXCEPTION_COULDNOT_PREPARE_MATCHING_PARAMETERS {
            get {
                return ResourceManager.GetString("EXCEPTION_COULDNOT_PREPARE_MATCHING_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has wrong format. Configuration cannot be loaded..
        /// </summary>
        internal static string EXCEPTION_ER_FILE_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("EXCEPTION_ER_FILE_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchAI settings cannot be saved..
        /// </summary>
        internal static string EXCEPTION_ER_SETTINGS_NOT_SAVED {
            get {
                return ResourceManager.GetString("EXCEPTION_ER_SETTINGS_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during export. please try another file..
        /// </summary>
        internal static string EXCEPTION_EXPORT_FAIL {
            get {
                return ResourceManager.GetString("EXCEPTION_EXPORT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load data from source..
        /// </summary>
        internal static string EXCEPTION_IMPORTDATA_FAIL {
            get {
                return ResourceManager.GetString("EXCEPTION_IMPORTDATA_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master records could not be defined.
        /// </summary>
        internal static string EXCEPTION_MASTER_RECORD_CANNOT_BE_DEFINED {
            get {
                return ResourceManager.GetString("EXCEPTION_MASTER_RECORD_CANNOT_BE_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match result could not be processed.
        /// </summary>
        internal static string EXCEPTION_MATCH_RESULT_NOT_PROCESSED {
            get {
                return ResourceManager.GetString("EXCEPTION_MATCH_RESULT_NOT_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match result could not be updated.
        /// </summary>
        internal static string EXCEPTION_MATCH_RESULT_NOT_UPDATED {
            get {
                return ResourceManager.GetString("EXCEPTION_MATCH_RESULT_NOT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has wrong format. Matrix cannot be loaded..
        /// </summary>
        internal static string EXCEPTION_MATRIX_FILE_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("EXCEPTION_MATRIX_FILE_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data for export.
        /// </summary>
        internal static string EXCEPTION_NO_DATA_FOR_EXPORT {
            get {
                return ResourceManager.GetString("EXCEPTION_NO_DATA_FOR_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fields for table were selected.
        /// </summary>
        internal static string EXCEPTION_NO_FIELD_WERE_SELECTED {
            get {
                return ResourceManager.GetString("EXCEPTION_NO_FIELD_WERE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such table in current table list.
        /// </summary>
        internal static string EXCEPTION_NO_TABLE {
            get {
                return ResourceManager.GetString("EXCEPTION_NO_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set match parameters.\r\nYou should select table, select result fields and set match criteria..
        /// </summary>
        internal static string EXCEPTION_SET_MATCHING_PARAMETERS {
            get {
                return ResourceManager.GetString("EXCEPTION_SET_MATCHING_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics cannot be calculated.
        /// </summary>
        internal static string EXCEPTION_STATISTIC_CANNOT_BE_CALCULATED {
            get {
                return ResourceManager.GetString("EXCEPTION_STATISTIC_CANNOT_BE_CALCULATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo fail.
        /// </summary>
        internal static string EXCEPTION_UNDOFAIL {
            get {
                return ResourceManager.GetString("EXCEPTION_UNDOFAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo limit is 10,000 records per dataset. Only imported first 10,000 records.
        /// </summary>
        internal static string MESSAGE_DEMO_50_LIMITED {
            get {
                return ResourceManager.GetString("MESSAGE_DEMO_50_LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean and Match {0} has limit of {1} per dataset. Only imported first {1}.
        /// </summary>
        internal static string MESSAGE_DEMO_CAM_LIMITED {
            get {
                return ResourceManager.GetString("MESSAGE_DEMO_CAM_LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This edition has a limit of 10,000 records per dataset. Only imported first 10,000 records.
        /// </summary>
        internal static string MESSAGE_FREEEDITION_LIMITED {
            get {
                return ResourceManager.GetString("MESSAGE_FREEEDITION_LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to clean..
        /// </summary>
        internal static string MESSAGE_NO_DATA_FOR_CLEANING {
            get {
                return ResourceManager.GetString("MESSAGE_NO_DATA_FOR_CLEANING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was successfully cancelled.
        /// </summary>
        internal static string MESSAGE_OPERATION_WAS_CANCELLED {
            get {
                return ResourceManager.GetString("MESSAGE_OPERATION_WAS_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one data source.
        /// </summary>
        internal static string MESSAGE_SELECRERSOURCE {
            get {
                return ResourceManager.GetString("MESSAGE_SELECRERSOURCE", resourceCulture);
            }
        }
    }
}
